[package]
name = "dirstructcopy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
question = "0.2.2"
walkdir = "2"
termion = "*"